SUBJECTS = [
    {"subjectId": 1, "subjectName": "Limba și literatura română"},
    {"subjectId": 2, "subjectName": "Matematică"},
    {"subjectId": 3, "subjectName": "Biologie"},
    {"subjectId": 4, "subjectName": "Geografie"},
    {"subjectId": 5, "subjectName": "Fizică"},
    {"subjectId": 6, "subjectName": "Chimie"},
    {"subjectId": 7, "subjectName": "Istorie"},
    {"subjectId": 8, "subjectName": "TIC"},
    {"subjectId": 9, "subjectName": "Informatică"},
    {"subjectId": 10, "subjectName": "Logică, argumentare și comunicare"},
    {"subjectId": 11, "subjectName": "Filosofie"},
    {"subjectId": 12, "subjectName": "Limba engleză"},
]

TOPICS = [
    {"topicId": 1001, "subjectId": 1, "grade": 9, "topicName": "Norme ortografice și de punctuație"},
    {"topicId": 1002, "subjectId": 1, "grade": 9, "topicName": "Vocabular și sensuri ale cuvintelor"},
    {"topicId": 1003, "subjectId": 1, "grade": 9, "topicName": "Comunicare orală și scrisă"},
    {"topicId": 1004, "subjectId": 1, "grade": 9, "topicName": "Elemente de construcție a textului"},
    {"topicId": 1101, "subjectId": 2, "grade": 9, "topicName": "Mulțimi de numere și operații"},
    {"topicId": 1102, "subjectId": 2, "grade": 9, "topicName": "Ecuații și inecuații"},
    {"topicId": 1103, "subjectId": 2, "grade": 9, "topicName": "Funcții și reprezentare grafică"},
    {"topicId": 1104, "subjectId": 2, "grade": 9, "topicName": "Geometrie plană și relații metrice"},
    {"topicId": 1201, "subjectId": 3, "grade": 9, "topicName": "Organizarea lumii vii"},
    {"topicId": 1202, "subjectId": 3, "grade": 9, "topicName": "Celula: structură și funcții"},
    {"topicId": 1203, "subjectId": 3, "grade": 9, "topicName": "Țesuturi, organe și sisteme"},
    {"topicId": 1204, "subjectId": 3, "grade": 9, "topicName": "Biodiversitate și clasificare"},
    {"topicId": 1301, "subjectId": 4, "grade": 9, "topicName": "Relief și procese geomorfologice"},
    {"topicId": 1302, "subjectId": 4, "grade": 9, "topicName": "Atmosfera și clima"},
    {"topicId": 1303, "subjectId": 4, "grade": 9, "topicName": "Apele Terrei"},
    {"topicId": 1304, "subjectId": 4, "grade": 9, "topicName": "Medii naturale și protecția mediului"},
    {"topicId": 1401, "subjectId": 5, "grade": 9, "topicName": "Mărimi fizice și unități de măsură"},
    {"topicId": 1402, "subjectId": 5, "grade": 9, "topicName": "Mișcare și repaus"},
    {"topicId": 1403, "subjectId": 5, "grade": 9, "topicName": "Forțe și legile mișcării"},
    {"topicId": 1404, "subjectId": 5, "grade": 9, "topicName": "Energie mecanică"},
    {"topicId": 1501, "subjectId": 6, "grade": 9, "topicName": "Structura atomului"},
    {"topicId": 1502, "subjectId": 6, "grade": 9, "topicName": "Tabelul periodic"},
    {"topicId": 1503, "subjectId": 6, "grade": 9, "topicName": "Legături chimice"},
    {"topicId": 1504, "subjectId": 6, "grade": 9, "topicName": "Reacții chimice simple"},
    {"topicId": 1601, "subjectId": 7, "grade": 9, "topicName": "Introducere în studiul istoriei"},
    {"topicId": 1602, "subjectId": 7, "grade": 9, "topicName": "Civilizații și spații istorice"},
    {"topicId": 1603, "subjectId": 7, "grade": 9, "topicName": "Evul Mediu"},
    {"topicId": 1604, "subjectId": 7, "grade": 9, "topicName": "Instituții și societate medievală"},
    {"topicId": 1701, "subjectId": 8, "grade": 9, "topicName": "Concepte de bază ale TIC"},
    {"topicId": 1702, "subjectId": 8, "grade": 9, "topicName": "Sisteme de operare și fișiere"},
    {"topicId": 1703, "subjectId": 8, "grade": 9, "topicName": "Internet și siguranță digitală"},
    {"topicId": 1704, "subjectId": 8, "grade": 9, "topicName": "Editare documente și prezentări"},
    {"topicId": 1801, "subjectId": 9, "grade": 9, "topicName": "Algoritmi: noțiuni introductive"},
    {"topicId": 1802, "subjectId": 9, "grade": 9, "topicName": "Date de intrare și ieșire"},
    {"topicId": 1803, "subjectId": 9, "grade": 9, "topicName": "Structuri de control"},
    {"topicId": 1804, "subjectId": 9, "grade": 9, "topicName": "Pseudocod și scheme logice"},
    {"topicId": 1901, "subjectId": 10, "grade": 9, "topicName": "Termeni și noțiuni"},
    {"topicId": 1902, "subjectId": 10, "grade": 9, "topicName": "Definiții, clasificări și exemple în logică"},
    {"topicId": 1903, "subjectId": 10, "grade": 9, "topicName": "Logică propozițională și operatori logic"},
    {"topicId": 1904, "subjectId": 10, "grade": 9, "topicName": "Tipuri de rationamente"},
    {"topicId": 2001, "subjectId": 12, "grade": 9, "topicName": "Basic grammar structures"},
    {"topicId": 2002, "subjectId": 12, "grade": 9, "topicName": "Everyday vocabulary"},
    {"topicId": 2003, "subjectId": 12, "grade": 9, "topicName": "Phrasal Verbs"},
    {"topicId": 2004, "subjectId": 12, "grade": 9, "topicName": "Common Confusing Words"},
    {"topicId": 1005, "subjectId": 1, "grade": 10, "topicName": "Text literar și text nonliterar"},
    {"topicId": 1006, "subjectId": 1, "grade": 10, "topicName": "Moduri de expunere"},
    {"topicId": 1007, "subjectId": 1, "grade": 10, "topicName": "Figuri de stil și imagini artistice"},
    {"topicId": 1008, "subjectId": 1, "grade": 10, "topicName": "Redactarea textului argumentativ"},
    {"topicId": 1105, "subjectId": 2, "grade": 10, "topicName": "Funcții elementare"},
    {"topicId": 1106, "subjectId": 2, "grade": 10, "topicName": "Trigonometrie"},
    {"topicId": 1107, "subjectId": 2, "grade": 10, "topicName": "Vectori și geometrie analitică"},
    {"topicId": 1108, "subjectId": 2, "grade": 10, "topicName": "Sisteme de ecuații"},
    {"topicId": 1205, "subjectId": 3, "grade": 10, "topicName": "Funcțiile de nutriție la plante"},
    {"topicId": 1206, "subjectId": 3, "grade": 10, "topicName": "Funcțiile de relație la plante"},
    {"topicId": 1207, "subjectId": 3, "grade": 10, "topicName": "Funcțiile de reproducere"},
    {"topicId": 1208, "subjectId": 3, "grade": 10, "topicName": "Ecologie și ecosisteme"},
    {"topicId": 1305, "subjectId": 4, "grade": 10, "topicName": "Geografia Europei"},
    {"topicId": 1306, "subjectId": 4, "grade": 10, "topicName": "Uniunea Europeană"},
    {"topicId": 1307, "subjectId": 4, "grade": 10, "topicName": "Resurse și activități economice"},
    {"topicId": 1308, "subjectId": 4, "grade": 10, "topicName": "State și regiuni europene"},
    {"topicId": 1405, "subjectId": 5, "grade": 10, "topicName": "Fenomenul termic"},
    {"topicId": 1406, "subjectId": 5, "grade": 10, "topicName": "Lucru mecanic și putere"},
    {"topicId": 1407, "subjectId": 5, "grade": 10, "topicName": "Presiune și fluide"},
    {"topicId": 1408, "subjectId": 5, "grade": 10, "topicName": "Aplicații ale legilor fizicii"},
    {"topicId": 1505, "subjectId": 6, "grade": 10, "topicName": "Oxizi, acizi, baze, săruri"},
    {"topicId": 1506, "subjectId": 6, "grade": 10, "topicName": "Soluții și concentrații"},
    {"topicId": 1507, "subjectId": 6, "grade": 10, "topicName": "Clasificarea reacțiilor chimice"},
    {"topicId": 1508, "subjectId": 6, "grade": 10, "topicName": "Chimie anorganică aplicată"},
    {"topicId": 1605, "subjectId": 7, "grade": 10, "topicName": "Epoca modernă"},
    {"topicId": 1606, "subjectId": 7, "grade": 10, "topicName": "Revoluții și schimbări politice"},
    {"topicId": 1607, "subjectId": 7, "grade": 10, "topicName": "Statul modern român"},
    {"topicId": 1608, "subjectId": 7, "grade": 10, "topicName": "Națiune și cetățenie"},
    {"topicId": 1705, "subjectId": 8, "grade": 10, "topicName": "Foi de calcul tabelar"},
    {"topicId": 1706, "subjectId": 8, "grade": 10, "topicName": "Baze de date: noțiuni de bază"},
    {"topicId": 1707, "subjectId": 8, "grade": 10, "topicName": "Prelucrarea informației"},
    {"topicId": 1708, "subjectId": 8, "grade": 10, "topicName": "Colaborare și etică digitală"},
    {"topicId": 1805, "subjectId": 9, "grade": 10, "topicName": "Tablouri unidimensionale"},
    {"topicId": 1806, "subjectId": 9, "grade": 10, "topicName": "Matrice"},
    {"topicId": 1807, "subjectId": 9, "grade": 10, "topicName": "Subprograme"},
    {"topicId": 1808, "subjectId": 9, "grade": 10, "topicName": "Algoritmi de bază pe date numerice"},
    {"topicId": 2005, "subjectId": 12, "grade": 10, "topicName": "Tenses and sentence structure"},
    {"topicId": 2006, "subjectId": 12, "grade": 10, "topicName": "Vocabulary for education and society"},
    {"topicId": 2007, "subjectId": 12, "grade": 10, "topicName": "Written messages and short essays"},
    {"topicId": 2008, "subjectId": 12, "grade": 10, "topicName": "Understanding spoken and written texts"},
    {"topicId": 1009, "subjectId": 1, "grade": 11, "topicName": "Curente literare"},
    {"topicId": 1010, "subjectId": 1, "grade": 11, "topicName": "Genuri și specii literare"},
    {"topicId": 1011, "subjectId": 1, "grade": 11, "topicName": "Caracterizarea personajului"},
    {"topicId": 1012, "subjectId": 1, "grade": 11, "topicName": "Eseul literar"},
    {"topicId": 1109, "subjectId": 2, "grade": 11, "topicName": "Limite de funcții"},
    {"topicId": 1110, "subjectId": 2, "grade": 11, "topicName": "Continuitate"},
    {"topicId": 1111, "subjectId": 2, "grade": 11, "topicName": "Derivabilitate"},
    {"topicId": 1112, "subjectId": 2, "grade": 11, "topicName": "Probabilități și elemente de statistică"},
    {"topicId": 1209, "subjectId": 3, "grade": 11, "topicName": "Digestia și absorbția"},
    {"topicId": 1210, "subjectId": 3, "grade": 11, "topicName": "Respirația și circulația"},
    {"topicId": 1211, "subjectId": 3, "grade": 11, "topicName": "Excreția și homeostazia"},
    {"topicId": 1212, "subjectId": 3, "grade": 11, "topicName": "Sistemul nervos și endocrin"},
    {"topicId": 1309, "subjectId": 4, "grade": 11, "topicName": "Geografia populației"},
    {"topicId": 1310, "subjectId": 4, "grade": 11, "topicName": "Așezări umane și urbanizare"},
    {"topicId": 1311, "subjectId": 4, "grade": 11, "topicName": "Economia mondială"},
    {"topicId": 1312, "subjectId": 4, "grade": 11, "topicName": "Globalizare și dezvoltare durabilă"},
    {"topicId": 1409, "subjectId": 5, "grade": 11, "topicName": "Electricitate"},
    {"topicId": 1410, "subjectId": 5, "grade": 11, "topicName": "Curent electric și circuite"},
    {"topicId": 1411, "subjectId": 5, "grade": 11, "topicName": "Magnetism"},
    {"topicId": 1412, "subjectId": 5, "grade": 11, "topicName": "Inducție electromagnetică"},
    {"topicId": 1509, "subjectId": 6, "grade": 11, "topicName": "Hidrocarburi"},
    {"topicId": 1510, "subjectId": 6, "grade": 11, "topicName": "Compuși organici cu funcțiuni simple"},
    {"topicId": 1511, "subjectId": 6, "grade": 11, "topicName": "Izomerie"},
    {"topicId": 1512, "subjectId": 6, "grade": 11, "topicName": "Reacții în chimia organică"},
    {"topicId": 1609, "subjectId": 7, "grade": 11, "topicName": "Secolul al XIX-lea"},
    {"topicId": 1610, "subjectId": 7, "grade": 11, "topicName": "România modernă"},
    {"topicId": 1611, "subjectId": 7, "grade": 11, "topicName": "Relații internaționale"},
    {"topicId": 1612, "subjectId": 7, "grade": 11, "topicName": "Societate și ideologii"},
    {"topicId": 1809, "subjectId": 9, "grade": 11, "topicName": "Recursivitate"},
    {"topicId": 1810, "subjectId": 9, "grade": 11, "topicName": "Sortări și căutări"},
    {"topicId": 1811, "subjectId": 9, "grade": 11, "topicName": "Fișiere"},
    {"topicId": 1812, "subjectId": 9, "grade": 11, "topicName": "Algoritmi clasici"},
    {"topicId": 2101, "subjectId": 11, "grade": 11, "topicName": "Introducere în filosofie"},
    {"topicId": 2102, "subjectId": 11, "grade": 11, "topicName": "Cunoaștere și adevăr"},
    {"topicId": 2103, "subjectId": 11, "grade": 11, "topicName": "Valori și morală"},
    {"topicId": 2104, "subjectId": 11, "grade": 11, "topicName": "Om, libertate și responsabilitate"},
    {"topicId": 2009, "subjectId": 12, "grade": 11, "topicName": "Complex grammar and connectors"},
    {"topicId": 2010, "subjectId": 12, "grade": 11, "topicName": "Formal and informal writing"},
    {"topicId": 2011, "subjectId": 12, "grade": 11, "topicName": "Opinion and argument in English"},
    {"topicId": 2012, "subjectId": 12, "grade": 11, "topicName": "Media and intercultural communication"},
    {"topicId": 1013, "subjectId": 1, "grade": 12, "topicName": "Autori canonici"},
    {"topicId": 1014, "subjectId": 1, "grade": 12, "topicName": "Relația dintre operă și curent literar"},
    {"topicId": 1015, "subjectId": 1, "grade": 12, "topicName": "Particularități de construcție a personajului"},
    {"topicId": 1016, "subjectId": 1, "grade": 12, "topicName": "Eseu de tip bacalaureat"},
    {"topicId": 1113, "subjectId": 2, "grade": 12, "topicName": "Primitive și integrale"},
    {"topicId": 1114, "subjectId": 2, "grade": 12, "topicName": "Aplicații ale integralei"},
    {"topicId": 1115, "subjectId": 2, "grade": 12, "topicName": "Matrice și determinanți"},
    {"topicId": 1116, "subjectId": 2, "grade": 12, "topicName": "Sisteme liniare"},
    {"topicId": 1213, "subjectId": 3, "grade": 12, "topicName": "Genetică: noțiuni fundamentale"},
    {"topicId": 1214, "subjectId": 3, "grade": 12, "topicName": "Ereditate și variabilitate"},
    {"topicId": 1215, "subjectId": 3, "grade": 12, "topicName": "Evoluționism"},
    {"topicId": 1216, "subjectId": 3, "grade": 12, "topicName": "Biotehnologii și aplicații"},
    {"topicId": 1313, "subjectId": 4, "grade": 12, "topicName": "Geografia României: relief"},
    {"topicId": 1314, "subjectId": 4, "grade": 12, "topicName": "Geografia României: climă și ape"},
    {"topicId": 1315, "subjectId": 4, "grade": 12, "topicName": "Populația și economia României"},
    {"topicId": 1316, "subjectId": 4, "grade": 12, "topicName": "România în Europa"},
    {"topicId": 1413, "subjectId": 5, "grade": 12, "topicName": "Optică geometrică"},
    {"topicId": 1414, "subjectId": 5, "grade": 12, "topicName": "Optică ondulatorie"},
    {"topicId": 1415, "subjectId": 5, "grade": 12, "topicName": "Fizică modernă"},
    {"topicId": 1416, "subjectId": 5, "grade": 12, "topicName": "Aplicații și probleme recapitulative"},
    {"topicId": 1513, "subjectId": 6, "grade": 12, "topicName": "Compuși organici cu funcțiuni mixte"},
    {"topicId": 1514, "subjectId": 6, "grade": 12, "topicName": "Macromolecule și polimeri"},
    {"topicId": 1515, "subjectId": 6, "grade": 12, "topicName": "Biochimie elementară"},
    {"topicId": 1516, "subjectId": 6, "grade": 12, "topicName": "Aplicații ale chimiei organice"},
    {"topicId": 1613, "subjectId": 7, "grade": 12, "topicName": "Secolul XX"},
    {"topicId": 1614, "subjectId": 7, "grade": 12, "topicName": "România contemporană"},
    {"topicId": 1615, "subjectId": 7, "grade": 12, "topicName": "Regimuri politice și democrație"},
    {"topicId": 1616, "subjectId": 7, "grade": 12, "topicName": "Europa și lumea postbelică"},
    {"topicId": 1813, "subjectId": 9, "grade": 12, "topicName": "Structuri de date de bază"},
    {"topicId": 1814, "subjectId": 9, "grade": 12, "topicName": "Backtracking"},
    {"topicId": 1815, "subjectId": 9, "grade": 12, "topicName": "Grafuri: noțiuni introductive"},
    {"topicId": 1816, "subjectId": 9, "grade": 12, "topicName": "Analiza complexității"},
    {"topicId": 2105, "subjectId": 11, "grade": 12, "topicName": "Problema existenței"},
    {"topicId": 2106, "subjectId": 11, "grade": 12, "topicName": "Libertate și determinism"},
    {"topicId": 2107, "subjectId": 11, "grade": 12, "topicName": "Valori politice și sociale"},
    {"topicId": 2108, "subjectId": 11, "grade": 12, "topicName": "Argument filosofic aplicat"},
    {"topicId": 2013, "subjectId": 12, "grade": 12, "topicName": "Advanced reading comprehension"},
    {"topicId": 2014, "subjectId": 12, "grade": 12, "topicName": "Essay and review writing"},
    {"topicId": 2015, "subjectId": 12, "grade": 12, "topicName": "Grammar consolidation for exams"},
    {"topicId": 2016, "subjectId": 12, "grade": 12, "topicName": "Integrated communication tasks"},
]


class CurriculumCatalogService:
    def list_catalog(self, grade=None, subject_id=None, topic_id=None):
        topics = TOPICS

        if grade is not None:
            topics = [topic for topic in topics if topic["grade"] == grade]
        if subject_id is not None:
            topics = [topic for topic in topics if topic["subjectId"] == subject_id]
        if topic_id is not None:
            topics = [topic for topic in topics if topic["topicId"] == topic_id]

        subject_by_id = {subject["subjectId"]: subject for subject in SUBJECTS}
        subject_ids = {topic["subjectId"] for topic in topics}
        subjects = [
            subject for subject in SUBJECTS if subject["subjectId"] in subject_ids
        ]

        enriched_topics = [
            {
                **topic,
                "subjectName": subject_by_id[topic["subjectId"]]["subjectName"],
            }
            for topic in topics
        ]

        return {
            "subjects": subjects,
            "topics": enriched_topics,
        }
