class QuestionGenerationPromptService:
    def build_prompt(self, content: str, count: int) -> str:
        lesson_content = content.strip()

        return (
            "You are an educational question generation assistant.\n\n"
            f"Generate exactly {count} questions based only on the lesson content below.\n\n"
            "Return only valid JSON in this exact format:\n"
            "{\n"
            "  \"questions\": [\n"
            "    {\n"
            "      \"text\": \"...\",\n"
            "      \"type\": \"SINGLE_CHOICE\" or \"MULTIPLE_CHOICE\",\n"
            "      \"answers\": [\"...\", \"...\", \"...\", \"...\"],\n"
            "      \"correctAnswers\": [\"...\"],\n"
            "      \"difficulty\": 0.5\n"
            "    }\n"
            "  ]\n"
            "}\n\n"
            "Output contract:\n"
            "- Return a single JSON object and nothing else.\n"
            "- The top-level object must contain exactly one key: \"questions\".\n"
            f"- \"questions\" must be an array with exactly {count} items.\n"
            "- Every question object must contain exactly these keys: "
            "\"text\", \"type\", \"answers\", \"correctAnswers\", \"difficulty\".\n"
            "- \"type\" must be exactly \"SINGLE_CHOICE\" or \"MULTIPLE_CHOICE\".\n"
            "- \"answers\" must contain exactly 4 non-empty strings.\n"
            "- \"correctAnswers\" must contain exact string copies from \"answers\".\n"
            "- Do not paraphrase correct answers in \"correctAnswers\"; copy them "
            "character-for-character from \"answers\".\n"
            "- For SINGLE_CHOICE, \"correctAnswers\" must contain exactly 1 item.\n"
            "- For MULTIPLE_CHOICE, \"correctAnswers\" must contain at least 2 items.\n"
            "- \"difficulty\" must be a JSON number between 0.0 and 1.0, not a string.\n"
            "- Do not include comments, markdown, explanations, trailing commas, "
            "or text outside JSON.\n"
            "- Before returning, internally validate that the JSON can be parsed "
            "by JSON.parse and matches every rule above.\n\n"
            f"Rules:\n"
            f"- Generate exactly {count} questions.\n"
            "- The text field must contain only the question statement, without "
            "the correct answer or any hint that reveals it.\n"
            "- Each question must have 4 answer options.\n"
            "- correctAnswers must contain only values from answers.\n"
            "- difficulty must be between 0.0 and 1.0.\n"
            "- Do not return markdown.\n"
            "- Do not return explanations.\n"
            "- Use only the lesson content.\n\n"
            "- Write the questions in the Romanian language.\n\n"
            "- VERY IMPORTANT : DO NOT HALLUCINATE !\n\n"
            f"Lesson content:\n{lesson_content}\n"
        )
