# Generated by Django 6.0.4 on 2026-04-10 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_id', models.IntegerField()),
                ('topic_id', models.IntegerField()),
                ('question_type', models.CharField(choices=[('single_choice', 'Single Choice'), ('multiple_choice', 'Multiple Choice')], max_length=20)),
                ('content', models.TextField()),
                ('difficulty', models.FloatField(default=0.5)),
                ('is_active', models.BooleanField(default=True)),
                ('times_answered', models.IntegerField(default=0)),
                ('times_correct', models.IntegerField(default=0)),
                ('avg_time_spent', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('display_order', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='tutoring.question')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionCorrectOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correct_options', to='tutoring.question')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correct_for_questions', to='tutoring.questionoption')),
            ],
        ),
        migrations.CreateModel(
            name='StudentInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('is_correct', models.BooleanField()),
                ('score', models.FloatField(default=0.0)),
                ('time_spent', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='tutoring.question')),
            ],
        ),
    ]
