# Generated by Django 5.2.13 on 2026-04-29 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='ml_exercise_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='studentinteraction',
            name='ml_exercise_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
