# Generated by Django 6.0.3 on 2026-04-01 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='difficulty_initial',
            new_name='difficulty',
        ),
        migrations.RemoveField(
            model_name='question',
            name='difficulty_observed',
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('single_choice', 'Single Choice'), ('multiple_choice', 'Multiple Choice')], default='single_choice', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentinteraction',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='tutoring.question'),
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('display_order', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='tutoring.question')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionCorrectOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correct_options', to='tutoring.question')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correct_for_questions', to='tutoring.questionoption')),
            ],
        ),
    ]
