# Generated by Django 6.0.4 on 2026-04-26 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentTopicLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_id', models.IntegerField()),
                ('topic_id', models.IntegerField()),
                ('mastery_score', models.FloatField(default=0.5)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutoring.studentprofile')),
            ],
            options={
                'unique_together': {('student', 'subject_id', 'topic_id')},
            },
        ),
    ]
