# Generated by Django 6.0.4 on 2026-04-29 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tutoring", "0002_question_ml_exercise_id_and_more"),
        ("tutoring", "0002_studentprofile_studenttopiclevel"),
    ]

    operations = []
