# Generated by Django 6.0.4 on 2026-04-29 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutoring", "0003_merge_20260429_1955"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentinteraction",
            name="user_id",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="student_id",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
